- name: allerai-event-handler-input-sub
  topic: allerai-scorer-events
  push_endpoint: https://allerai-event_handler-400287020576.europe-north2.run.app

- name: allerai-scorer-events-bq-sub
  topic: allerai-scorer-events
  bigquery_table: pubsub_events.input_events

- name: allerai-scorer-events-push-bq-sub
  topic: allerai-scorer-events-push
  bigquery_table: pubsub_events.output_events
