- name: allerai-event-handler-input-subscription
  topic: allerai-scorer-events
  push_endpoint: https://allerai-event-handler-400287020576.europe-north2.run.app

- name: allerai-enrichment-push-test-subscription
  topic: allerai-enrichment-push-test
  push_endpoint: https://allerai-scorer-400287020576.europe-north2.run.app

- name: allerai-scorer-events-bq-subscription
  topic: allerai-scorer-events
  bigquery_table: pubsub_events.input_events
  deadletter_topic: allerai-scorer-events-dlt

- name: allerai-scorer-events-error-log-bq-subscription
  topic: allerai-scorer-events-error-log
  bigquery_table: pubsub_events.input_events_error_log

- name: allerai-scorer-events-push-bq-subscription
  topic: allerai-scorer-events-push
  bigquery_table: pubsub_events.output_events
  deadletter_topic: allerai-scorer-events-push-dlt

- name: allerai-scorer-events-push-error-log-bq-subscription
  topic: allerai-scorer-events-push-error-log
  bigquery_table: pubsub_events.output_events_error_log
