name: Build, Push Docker Image and Deploy with Terraform

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/deploy_service.yaml
      - "event_scorer/app/**"
      - event_scorer/Dockerfile

  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA }}

      - name: Configure Docker client
        run: |
          gcloud auth configure-docker europe-docker.pkg.dev

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: scorer
          push: true
          tags: europe-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/docker/allerai-scorer:latest

  update-service:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Deploy new image to Cloud Run
        run: |
          SERVICE_NAME="allerai-scorer"
          IMAGE_URL="europe-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/docker/allerai-scorer:latest"
          REGION=europe-north2

          # Check if the service already exists
          if gcloud run services describe ${SERVICE_NAME} --region=${REGION} &> /dev/null; then
            # Update existing service
            gcloud run services update ${SERVICE_NAME} \
              --image=${IMAGE_URL} \
              --region=${REGION}
          else
            echo "INFO: Service not found. Please deploy service with infrastructure code first."
          fi
